/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263hw01;

import org.apache.commons.cli.*;

public class App {

    public static void main(String[] args) {

    }

    public static void cLIOptions() throws ParseException {
        Options options = new Options();
        Option option1 = new Option("-b","--batch");
        options.addOption(option1);

        Option option2 = new Option("-h", "--help");
        options.addOption(option2);

        Option option3 = new Option("-o", "--output");
        options.addOption(option3);

        CommandLineParser commandLineParser = new DefaultParser();
        String[] arguments = new String[]{"-b", "-h", "-o"};
        CommandLine commandLine = commandLineParser.parse(options, arguments);
        
    }
}
